language: php
php:
- 7.1
- 7.0
deploy:
  provider: heroku
  api_key:
    secure: E89zkg/5fRE3BmRrK24ls0ZZ+sQLGAiK/5oXsL/Zi2wbV8zPJkfjuIUspgnIhIE/+Vo2mi+1Sg05xevqZetDfRkXomarB5lxbk/ncPRjKXxXhGUwIIGB/Y0xnkzw21QSyduOPuAJhmuGeOBmc8zsPXlsrqo0KLhkUVe4U1EKdsLvJUkDYem/+/gyFylNc3fm3Clp/r9EdFofk1myTUW22eN8lTQkLUcotrIHq79Iy3N1JXwqq9eIvnwTADjw3QeP9gCj+DcwCHN3NGKBSwooqieWyy7rOpyoPWB2+BMiV+MFMNCEqyeVZILokXlsRYV2TqJsWU8PDUuS9ArCGKppv+Vs+pC+WgInyELSbu/z38H6WU5BZWs5WoG3Zr/IP+G3vTk9zz6wkBctNKMX8Uc6RZY/2Evs3Dq2lyEDZax53m065o3nK/5UtANCNYPoXskSh2oit4wAQp+7OjdY/SV/k4C1iJShnTopSBZmoAA9qng+wrn0JI/tlejJRRz8sU/1xwnB8pFgri3VDvVCkdoAsCgrAHQeOMKts7Ezv4RsttVSuYQk2BF9WKjrXjhfFz0L+8lnnmWoGsIE7QKtDfajNdsz4+M7oCvbxWBwAiRaAjtR+DajObCFUufuOLrQPrYofFf2wsBbQcpTUMxJKxUldI+csnWTiwoddZnDDJzisOc=
  app: helloefe
script:
- "$TRAVIS_BUILD_DIR/vendor/bin/phpunit tests/test"
