language: php
php:
- 7.1
- 7.0
deploy:
  provider: heroku
  api_key:
    secure: RgafUDe+pan2QV2hVWFER9asmzCXiLcRHyc/KAflxlsjmZRLdn08QZ/xWf/lqQcD9AzF95JLfG+EZUYDULzPPpEZxPUvZUR3NyF7BgykhYCNWwdPkTa3e5B8R+OKA9VN2wk/wY1wBCnLwNzyp46c1B1IuV9QWTS3NVWq0iFcXzBYyK1D3bnOXcjmjUrrmD8BSFkeBRh2/nH9d/uLcH+ekIoqkcfyC3bP3NaH0FV3MYCEr3pC3ovWe51vxAs29neTLF5BvPFWBBErxd1XeHpuCIiZWZz7xk3oK9Ig7HMDi3otl1gj8LtBNdWDULIKRoLBzuw8uycN/+wBBl7pIT6yjQ+ICFcI5GiBcANigiY7oUy4rEdyaPSDnY1lrNi7jnEXpth2NQz+Y5KpRzd2W82QjvV+POuhFtuhtkqjkn24SjjWF/fQg836eduPC/7eOrEmi3r6zGuHq4QfG6RQ4ayiZCWJfAUgfY5My9KnEwVTMXKnMIG8nw0544GeGmi30KnpblVraVpv8F1cneL9xGNL4LZjVncYVJM8REAd+xf2LFdoDWPXlxDk2w+LztKuNuj5w+3k0R1Dq7W4MQP+W6YY7JfT1WTV76mTZaUnFSV4HQIKpVKzrzEC8i98quyNXyiuw4la5ai894T1c/mA1i8Fg+wGe0tnAHqNX4Yzb5D9zJk=
script:
- "$TRAVIS_BUILD_DIR/vendor/bin/phpunit tests/test"
