language: php


before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar

php:
  - 5.4
  - 5.5

deploy:
  provider: heroku
  api_key:
    secure: CumnVtM0bH3BbdI0SLEZXcKwwPFLtvW/eMzUq/WZ5AH+iKNZXClZNHesa5LVEMfReAjgZ+DIDdnNP+sqjWuSaMEiY5uJ1q6yxrIEYQfWLmT/fbmC+NmH0m4XIVyecnx0hFq9lgsO10koiS/RcHwE+2wwNW0tyM5BuedXbxfKJWTxD2wt9Kkm5q3bWZ46LTvJgJfM3lEMJ/p89No5Gfwlh3pBfjcH6Qx2b+WM0ZDHmS180VfatfC0BruTpowUPPQMlpJlbq/mSIM7+e8JCWgabpCU/iJPpxD6Y6Hmchz19r00Ov3/Rg5KecmKOzRQgs+u9JnVTPA8Z14+UCTEBqe4RoGiWJjPcXTFgj803BWORgg9B/xhIPQLew1jDd/8thaycp3PGFbu5gqaWs1rKkiwE/hpOvLNs858BnkEkw3FBYn4M+mkALI+bFxTo/8q7QiH0ySXjYjFoqSNL/6mEFT9dCVFv2PvGq+Q2wZlyHki6onehGHAQe9RZeeF8tWQQcs7zJWTfF873xlnk9uF1uptxp8DoAaUJajwlw2DB9rcIjFsq7afb3zBpI7ZKqKFLzxhmPPtbtzSodhB4emS9LPsSJ2K5AcVw1InLTmJMoYi4m6kX1S/Sgxpz1q7n/ia8c6BgzlW6Cfb6pTG/2zdMcjigWvbl1id0g9Trri3r/PyDAc=

script:
  - phpunit --bootstrap vendor/autoload.php tests/test

